services:
  zeebe:
    image: camunda/zeebe:8.5.3
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=zeebe
      - ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_GATEWAY_NETWORK_PORT=26500
    volumes:
      - ./zeebe-application.yaml:/usr/local/zeebe/config/application.yaml
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  tribe:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tribe
    container_name: tribe-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - LOGGING_LEVEL_ROOT=INFO
      - ZEEBE_CLIENT_GATEWAY_ADDRESS=zeebe:26500
      # JWT_SECRET must be provided externally 
      # Example: JWT_SECRET=$(openssl rand -base64 32)
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      zeebe:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: tribe-frontend
    ports:
      - "80:80"
    depends_on:
      tribe:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  tribe-data: